DROP TABLE IF EXISTS globals;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bowtypes;
DROP TABLE IF EXISTS bows;
